# Generated by Django 4.1.7 on 2023-03-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_area', models.CharField(blank=True, max_length=10, verbose_name='Logradouro')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('district', models.CharField(max_length=128, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('crated_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateField(null=True, verbose_name='Deletado em')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.person')),
                ('coffito', models.CharField(max_length=14, verbose_name='Coffito')),
            ],
            bases=('appointment.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.person')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('occupations', models.TextField(verbose_name='Ocupação')),
                ('civil_status', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)')], default='S', max_length=1, verbose_name='Status civil')),
                ('pathologies', models.TextField(blank=True, null=True, verbose_name='Patologias')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.address', verbose_name='Endereço')),
            ],
            bases=('appointment.person',),
        ),
    ]
