# Generated by Django 4.1.7 on 2023-04-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('return_date', models.DateField(null=True, verbose_name='Próxima avaliação')),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='prescriber',
            options={'verbose_name': 'Fisioterapeuta', 'verbose_name_plural': 'Fisioterapeutas'},
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='coffito',
            field=models.CharField(max_length=14, verbose_name='Registro'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('assessment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.assessment')),
                ('blood_pressure', models.CharField(max_length=10, null=True, verbose_name='Pressão arterial')),
                ('spo2', models.IntegerField(null=True, verbose_name='Saturação(SPO2)')),
                ('heart_rate', models.IntegerField(null=True, verbose_name='Frequência cardíaca')),
                ('respiratory_rate', models.IntegerField(null=True, verbose_name='Frequência respiratória')),
                ('temperature', models.FloatField(null=True, verbose_name='Temperatura')),
                ('left_goniometry', models.JSONField(null=True, verbose_name='Goniômetro - Esquerda')),
                ('right_goniometry', models.JSONField(null=True, verbose_name='Goniômetro - Direita')),
                ('eva', models.IntegerField(null=True, verbose_name='Escala de dor(EVA)')),
                ('glasgow', models.JSONField(null=True, verbose_name='Escala Glasgow')),
                ('palpation', models.TextField(null=True, verbose_name='Palpação')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
            bases=('appointment.assessment',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('assessment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.assessment')),
                ('age', models.IntegerField(null=True, verbose_name='Idade')),
                ('birth_date', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('height', models.FloatField(null=True, verbose_name='Altura')),
                ('goal', models.CharField(max_length=10, null=True, verbose_name='Objetivos')),
                ('physical_activity', models.TextField(null=True, verbose_name='Pratica atividades fisicas? Quais?')),
                ('medication', models.TextField(null=True, verbose_name='Utiliza medicação? Qual?')),
                ('smoker', models.BooleanField(default=False, verbose_name='Tabagista?')),
                ('alcoholic', models.BooleanField(default=False, verbose_name='Etilista?')),
                ('hypertensive', models.BooleanField(default=False, verbose_name='Hipertenso?')),
                ('diabetic', models.BooleanField(default=False, verbose_name='Diabético?')),
                ('sedentary', models.BooleanField(default=False, verbose_name='Sedentário?')),
                ('pain', models.TextField(null=True, verbose_name='Dor? Quais?')),
                ('surgery', models.TextField(null=True, verbose_name='Sirurgia? Quais?')),
                ('hpa', models.TextField(null=True, verbose_name='História do problema atual(HPA)')),
                ('hpp', models.TextField(null=True, verbose_name='História patológica  progressiva(HPP)')),
                ('complementary_exams', models.TextField(null=True, verbose_name='Exames complementares')),
                ('biggest_complaint', models.CharField(max_length=10, null=True, verbose_name='Queixa principal')),
                ('family_background', models.TextField(null=True, verbose_name='Antecedentes familiares')),
                ('habits', models.TextField(null=True, verbose_name='Hábitos')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
            bases=('appointment.assessment',),
        ),
        migrations.AddField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.prescriber', verbose_name='Fisioterapeuta'),
        ),
    ]
