# Generated by Django 4.1.7 on 2023-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_assessment_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', max_length=1, verbose_name='Status civil'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hpp',
            field=models.TextField(null=True, verbose_name='História patológica progressiva(HPP)'),
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Cabeçalho')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.patient', verbose_name='Paciente')),
                ('prescriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.prescriber', verbose_name='Fisioterapeuta')),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
            },
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Cabeçalho')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('evolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.evolution', verbose_name='Evolução')),
            ],
            options={
                'verbose_name': 'Conduta',
                'verbose_name_plural': 'Condutas',
            },
        ),
    ]
