# Generated by Django 4.1.7 on 2023-08-23 00:26

import appointment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_quiz_birth_date_quiz_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[appointment.validators.cpf_validator], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, validators=[appointment.validators.name_validator], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[appointment.validators.phone_validator], verbose_name='Telefone'),
        ),
    ]
