name: Run Tests
on: push
jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: 3.10
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: cd backend
            python src/manage.py test
      - name: Run Linting
        run: cd backend
            python -m flake8
